### ISSUE TITLE
Test not passing on MacBook Pro 

### ISSUE THREAD

**Issue by ericagol** [langfzac/Photodynamics.jl#21]
macOS Monterey Version 12.3.1

MacBook Pro (Retina, 15-inch, Mid 2015)

Processor 2.8 GHz Quad-Core Intel Core i7

Julia v1.7.2

Test failed for Photodynamics.jl package running on the main branch:

```
     Testing Running tests...
Integration Methods... Done.
Impact Parameter... Done.
Lightcurve...   0.012285 seconds (83.17 k allocations: 12.065 MiB)
  0.024574 seconds (83.19 k allocations: 12.068 MiB, 47.56% gc time)
  0.004223 seconds (5.69 k allocations: 606.454 KiB, 78.28% compilation time)
  0.003783 seconds (5.71 k allocations: 608.688 KiB, 74.96% compilation time)
  0.001978 seconds (5.77 k allocations: 619.859 KiB)
  0.001894 seconds (5.80 k allocations: 622.703 KiB)
Lightcurve: Test Failed at /Users/ericagol/Software/Photodynamics.jl/test/test_compute_lightcurve.jl:53
  Expression: isapprox_maxabs(dlc_p.flux, lc_p.flux)
Stacktrace:
 [1] macro expansion
   @ /usr/local/Cellar/julia/1.7.2/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/Software/Photodynamics.jl/test/test_compute_lightcurve.jl:53 [inlined]
 [3] macro expansion
   @ /usr/local/Cellar/julia/1.7.2/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [4] top-level scope
   @ ~/Software/Photodynamics.jl/test/test_compute_lightcurve.jl:4
Lightcurve: Test Failed at /Users/ericagol/Software/Photodynamics.jl/test/test_compute_lightcurve.jl:54
  Expression: isapprox_maxabs(dlc_c.flux, lc_c.flux)
Stacktrace:
 [1] macro expansion
   @ /usr/local/Cellar/julia/1.7.2/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/Software/Photodynamics.jl/test/test_compute_lightcurve.jl:54 [inlined]
 [3] macro expansion
   @ /usr/local/Cellar/julia/1.7.2/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [4] top-level scope
   @ ~/Software/Photodynamics.jl/test/test_compute_lightcurve.jl:4
Test Summary:           | Pass  Fail  Total
Photodynamics.jl        |   65     2     67
  Integration Methods   |    4            4
  Impact Parameter      |   30           30
  Lightcurve            |   31     2     33
    Integrated Flux     |   14           14
    Non-Integrated Flux |   14           14
    Lightcurve          |    2     2      4
ERROR: LoadError: Some tests did not pass: 65 passed, 2 failed, 0 errored, 0 broken.
in expression starting at /Users/ericagol/Software/Photodynamics.jl/test/runtests.jl:6
ERROR: Package Photodynamics errored during testing

(Photodynamics) pkg> st
     Project Photodynamics v0.1.0
      Status `~/Software/Photodynamics.jl/Project.toml`
  [01eff828] Limbdark v0.1.0
  [69f646f0] NbodyGradient v0.1.3
  [189a3867] Reexport v1.2.2
  [f2b01f46] Roots v2.0.1
  [276daf66] SpecialFunctions v1.8.6
  [90137ffa] StaticArrays v1.4.7
  [37e2e46d] LinearAlgebra
```

This is perplexing since the tests pass for MacOS.  The difference is in the light curves with
and without derivatives computed. @langfzac thinks this is due to a difference in the
Limbdark.jl package, and may be a result of architecture-dependent differences in the
computation of special functions (perhaps logGamma?).

**Comment by ericagol** [comment]
Hi @langfzac -

If there is some issue with Limbdark.jl on the MacBook Pro machine causing the tests to fail, one way we could track this down would be to save & compare the individual values of the flux evaluated at each instant of time (rather than compare time-integrated fluxes).  Since the time-integrated values have a 10^{-8} discrepancy, then we should see an even larger discrepancy for a subset of the individual values.

-Eric

**Comment by langfzac** [comment]
@ericagol #22 adds the non-integrated exposure version to the tests, and outputs the maxabs of the differences.

**Comment by ericagol** [comment]
I'm thinking of adding a debugging option in which the flux is computed with & without derivatives (in the gradient case), and flagging individual flux points which differ by more than, say, 1e-8.

**Comment by langfzac** [comment]
@ericagol Can you paste the output of `versioninfo()` here? I'm wondering if there's a difference in LLVM versions or something

**Comment by ericagol** [comment]
Yes:

```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.3.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
```

**Comment by ericagol** [comment]
This came down to this issue with Limbdark.jl:

https://github.com/rodluger/Limbdark.jl/issues/94

When the gradient & non-gradient expressions were made to match, the
Photodynamics.jl no longer gets tripped up by the `b=1-r` example we
tried.   The Limbdark.jl tests pass, and the Photodynamics.jl tests pass on
the MacBook described above.

**Comment by ericagol** [comment]
With this fix, updated Limbdark.jl to v0.1.1.  This should allow tests to pass on MacBook.
